### **Basic SQL**

In [1]:
# Set-up
%load_ext sql
%sql sqlite://
import pandas as pd

In [2]:
# Choose files Cities.csv and Countries.csv to upload - must be on local computer
# If running notebook on local computer:
#   No need to run this cell (it will generate an error)
#   Make sure data files are in same workspace as notebook
from google.colab import files
uploaded = files.upload()

Saving Cities.csv to Cities.csv
Saving Countries.csv to Countries.csv

In [3]:
# Create database tables from CSV files
with open('Cities.csv') as f: Cities = pd.read_csv(f, index_col=0)
%sql drop table if exists Cities;
%sql --persist Cities
with open('Countries.csv') as f: Countries = pd.read_csv(f, index_col=0)
%sql drop table if exists Countries;
%sql --persist Countries

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.
 * sqlite://

'Persisted countries'

#### Look at sample of Cities and Countries tables

In [4]:
%%sql
select * from Cities limit 5

 * sqlite://
Done.

[('Aalborg', 'Denmark', 57.03, 9.92, 7.52),
 ('Aberdeen', 'United Kingdom', 57.17, -2.08, 8.1),
 ('Abisko', 'Sweden', 63.35, 18.83, 0.2),
 ('Adana', 'Turkey', 36.99, 35.32, 18.67),
 ('Albacete', 'Spain', 39.0, -1.87, 12.62)]

In [5]:
%%sql
select * from Countries limit 5

 * sqlite://
Done.

[('Albania', 2.9, 'no', 'yes'),
 ('Andorra', 0.07, 'no', 'no'),
 ('Austria', 8.57, 'yes', 'no'),
 ('Belarus', 9.48, 'no', 'no'),
 ('Belgium', 11.37, 'yes', 'yes')]

### Basic Select statement
Select columns  
From tables  
Where condition

*Find all countries not in the EU*

In [6]:
%%sql
select country
from Countries
where EU = 'no'

 * sqlite://
Done.

[('Albania',),
 ('Andorra',),
 ('Belarus',),
 ('Bosnia and Herzegovina',),
 ('Iceland',),
 ('Kosovo',),
 ('Liechtenstein',),
 ('Macedonia',),
 ('Moldova',),
 ('Montenegro',),
 ('Norway',),
 ('Serbia',),
 ('Switzerland',),
 ('Turkey',),
 ('Ukraine',)]

*Find all cities with temperature between -5 and 5; return city, country, and temperature*

In [9]:
%%sql
select city, country, temperature
from Cities
where temperature > -5 and temperature < 5
 order by country, temperature desc

 * sqlite://
Done.

[('Salzburg', 'Austria', 4.62),
 ('Innsbruck', 'Austria', 4.54),
 ('Orsha', 'Belarus', 4.93),
 ('Tallinn', 'Estonia', 4.82),
 ('Tartu', 'Estonia', 4.36),
 ('Turku', 'Finland', 4.72),
 ('Helsinki', 'Finland', 4.19),
 ('Tampere', 'Finland', 3.59),
 ('Oulu', 'Finland', 1.45),
 ('Augsburg', 'Germany', 4.54),
 ('Trondheim', 'Norway', 4.53),
 ('Bodo', 'Norway', 4.5),
 ('Oslo', 'Norway', 2.32),
 ('Bergen', 'Norway', 1.75),
 ('Uppsala', 'Sweden', 4.17),
 ('Abisko', 'Sweden', 0.2),
 ('Kiruna', 'Sweden', -2.2)]

### Ordering

*Modify previous query to sort by temperature*

*Modify previous query to sort by country, then temperature descending*

### <font color = 'green'>**Your Turn**</font>

*Find all countries with no coastline and with population > 9. Return the country and population, in descending order of population.*

In [16]:
%%sql
#YOUR QUERY HERE
select coastline, country, population
from Countries
where coastline = 'no' and population > 9 
 order by population desc

 * sqlite://
(sqlite3.OperationalError) near "YOUR": syntax error
[SQL: YOUR QUERY HERE
select coastline, country, population
from Countries
where coastline = 'no' and population > 9
 order by population desc]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

### Multiple tables in From clause - Joins

*Find all cities with longitude < 10 not in the EU, return city and longitude*

In [14]:
%%sql
select city, longitude
from Cities, Countries
where Cities.country = Countries.country
and longitude < 10 and EU = 'no'

 * sqlite://
Done.

[('Andorra', 1.52),
 ('Basel', 7.59),
 ('Bergen', 5.32),
 ('Geneva', 6.14),
 ('Stavanger', 5.68),
 ('Zurich', 8.56)]

*Modify previous query to also return country (error then fix)*

*Find all cities with latitude < 50 in a country with population < 5; return city, country, and population, sorted by country*

In [17]:
%%sql
select city, Cities.country, population
from Cities, Countries
where Cities.country = Countries.country
and latitude < 50 and population < 5
order by Cities.country

 * sqlite://
Done.

[('Elbasan', 'Albania', 2.9),
 ('Andorra', 'Andorra', 0.07),
 ('Sarajevo', 'Bosnia and Herzegovina', 3.8),
 ('Rijeka', 'Croatia', 4.23),
 ('Split', 'Croatia', 4.23),
 ('Skopje', 'Macedonia', 2.08),
 ('Balti', 'Moldova', 4.06),
 ('Chisinau', 'Moldova', 4.06),
 ('Podgorica', 'Montenegro', 0.63),
 ('Ljubljana', 'Slovenia', 2.07)]

#### Inner Join -- just FYI

*Same query as above*

In [18]:
%%sql
select city, Cities.country, population
from Cities inner join Countries
     on Cities.country = Countries.country
where latitude < 50 and population < 5
order by Cities.country

 * sqlite://
Done.

[('Elbasan', 'Albania', 2.9),
 ('Andorra', 'Andorra', 0.07),
 ('Sarajevo', 'Bosnia and Herzegovina', 3.8),
 ('Rijeka', 'Croatia', 4.23),
 ('Split', 'Croatia', 4.23),
 ('Skopje', 'Macedonia', 2.08),
 ('Balti', 'Moldova', 4.06),
 ('Chisinau', 'Moldova', 4.06),
 ('Podgorica', 'Montenegro', 0.63),
 ('Ljubljana', 'Slovenia', 2.07)]

### Select *

*Modify previous queries to return all columns*

### <font color = 'green'>**Your Turn**</font>

*Find all cities with latitude > 45 in a country with no coastline and with population > 9. Return the city, country, latitude, and whether it's in the EU.*

In [26]:
%%sql
select latitude, coastline, city, population, EU
from Countries, Cities
where coastline= 'no' and latitude > 45 and population > 9 and EU='yes'

 * sqlite://
Done.

[(57.03, 'no', 'Aalborg', 9.82, 'yes'),
 (57.03, 'no', 'Aalborg', 10.55, 'yes'),
 (57.17, 'no', 'Aberdeen', 9.82, 'yes'),
 (57.17, 'no', 'Aberdeen', 10.55, 'yes'),
 (63.35, 'no', 'Abisko', 9.82, 'yes'),
 (63.35, 'no', 'Abisko', 10.55, 'yes'),
 (49.9, 'no', 'Amiens', 9.82, 'yes'),
 (49.9, 'no', 'Amiens', 10.55, 'yes'),
 (52.35, 'no', 'Amsterdam', 9.82, 'yes'),
 (52.35, 'no', 'Amsterdam', 10.55, 'yes'),
 (47.48, 'no', 'Angers', 9.82, 'yes'),
 (47.48, 'no', 'Angers', 10.55, 'yes'),
 (46.17, 'no', 'Arad', 9.82, 'yes'),
 (46.17, 'no', 'Arad', 10.55, 'yes'),
 (48.35, 'no', 'Augsburg', 9.82, 'yes'),
 (48.35, 'no', 'Augsburg', 10.55, 'yes'),
 (46.58, 'no', 'Bacau', 9.82, 'yes'),
 (46.58, 'no', 'Bacau', 10.55, 'yes'),
 (47.66, 'no', 'Baia Mare', 9.82, 'yes'),
 (47.66, 'no', 'Baia Mare', 10.55, 'yes'),
 (47.76, 'no', 'Balti', 9.82, 'yes'),
 (47.76, 'no', 'Balti', 10.55, 'yes'),
 (47.58, 'no', 'Basel', 9.82, 'yes'),
 (47.58, 'no', 'Basel', 10.55, 'yes'),
 (54.6, 'no', 'Belfast', 9.82, 'yes'),
 (54.6, 'no', 'Belfast', 10.55, 'yes'),
 (45.7, 'no', 'Bergamo', 9.82, 'yes'),
 (45.7, 'no', 'Bergamo', 10.55, 'yes'),
 (60.39, 'no', 'Bergen', 9.82, 'yes'),
 (60.39, 'no', 'Bergen', 10.55, 'yes'),
 (52.52, 'no', 'Berlin', 9.82, 'yes'),
 (52.52, 'no', 'Berlin', 10.55, 'yes'),
 (53.15, 'no', 'Bialystok', 9.82, 'yes'),
 (53.15, 'no', 'Bialystok', 10.55, 'yes'),
 (52.03, 'no', 'Bielefeld', 9.82, 'yes'),
 (52.03, 'no', 'Bielefeld', 10.55, 'yes'),
 (49.77, 'no', 'Bila Tserkva', 9.82, 'yes'),
 (49.77, 'no', 'Bila Tserkva', 10.55, 'yes'),
 (52.47, 'no', 'Birmingham', 9.82, 'yes'),
 (52.47, 'no', 'Birmingham', 10.55, 'yes'),
 (53.83, 'no', 'Blackpool', 9.82, 'yes'),
 (53.83, 'no', 'Blackpool', 10.55, 'yes'),
 (67.25, 'no', 'Bodo', 9.82, 'yes'),
 (67.25, 'no', 'Bodo', 10.55, 'yes'),
 (50.72, 'no', 'Bonn', 9.82, 'yes'),
 (50.72, 'no', 'Bonn', 10.55, 'yes'),
 (47.75, 'no', 'Botosani', 9.82, 'yes'),
 (47.75, 'no', 'Botosani', 10.55, 'yes'),
 (50.73, 'no', 'Bournemouth', 9.82, 'yes'),
 (50.73, 'no', 'Bournemouth', 10.55, 'yes'),
 (53.8, 'no', 'Bradford', 9.82, 'yes'),
 (53.8, 'no', 'Bradford', 10.55, 'yes'),
 (45.29, 'no', 'Braila', 9.82, 'yes'),
 (45.29, 'no', 'Braila', 10.55, 'yes'),
 (48.15, 'no', 'Bratislava', 9.82, 'yes'),
 (48.15, 'no', 'Bratislava', 10.55, 'yes'),
 (53.08, 'no', 'Bremen', 9.82, 'yes'),
 (53.08, 'no', 'Bremen', 10.55, 'yes'),
 (48.39, 'no', 'Brest', 9.82, 'yes'),
 (48.39, 'no', 'Brest', 10.55, 'yes'),
 (52.1, 'no', 'Brest', 9.82, 'yes'),
 (52.1, 'no', 'Brest', 10.55, 'yes'),
 (49.2, 'no', 'Brno', 9.82, 'yes'),
 (49.2, 'no', 'Brno', 10.55, 'yes'),
 (51.22, 'no', 'Brugge', 9.82, 'yes'),
 (51.22, 'no', 'Brugge', 10.55, 'yes'),
 (47.5, 'no', 'Budapest', 9.82, 'yes'),
 (47.5, 'no', 'Budapest', 10.55, 'yes'),
 (53.12, 'no', 'Bydgoszcz', 9.82, 'yes'),
 (53.12, 'no', 'Bydgoszcz', 10.55, 'yes'),
 (50.35, 'no', 'Bytom', 9.82, 'yes'),
 (50.35, 'no', 'Bytom', 10.55, 'yes'),
 (49.18, 'no', 'Caen', 9.82, 'yes'),
 (49.18, 'no', 'Caen', 10.55, 'yes'),
 (52.2, 'no', 'Cambridge', 9.82, 'yes'),
 (52.2, 'no', 'Cambridge', 10.55, 'yes'),
 (50.83, 'no', 'Chemnitz', 9.82, 'yes'),
 (50.83, 'no', 'Chemnitz', 10.55, 'yes'),
 (49.43, 'no', 'Cherkasy', 9.82, 'yes'),
 (49.43, 'no', 'Cherkasy', 10.55, 'yes'),
 (51.5, 'no', 'Chernihiv', 9.82, 'yes'),
 (51.5, 'no', 'Chernihiv', 10.55, 'yes'),
 (48.31, 'no', 'Chernivtsi', 9.82, 'yes'),
 (48.31, 'no', 'Chernivtsi', 10.55, 'yes'),
 (47.01, 'no', 'Chisinau', 9.82, 'yes'),
 (47.01, 'no', 'Chisinau', 10.55, 'yes'),
 (51.9, 'no', 'Cork', 9.82, 'yes'),
 (51.9, 'no', 'Cork', 10.55, 'yes'),
 (55.88, 'no', 'Daugavpils', 9.82, 'yes'),
 (55.88, 'no', 'Daugavpils', 10.55, 'yes'),
 (47.53, 'no', 'Debrecen', 9.82, 'yes'),
 (47.53, 'no', 'Debrecen', 10.55, 'yes'),
 (47.33, 'no', 'Dijon', 9.82, 'yes'),
 (47.33, 'no', 'Dijon', 10.55, 'yes'),
 (53.33, 'no', 'Dublin', 9.82, 'yes'),
 (53.33, 'no', 'Dublin', 10.55, 'yes'),
 (56.47, 'no', 'Dundee', 9.82, 'yes'),
 (56.47, 'no', 'Dundee', 10.55, 'yes'),
 (55.95, 'no', 'Edinburgh', 9.82, 'yes'),
 (55.95, 'no', 'Edinburgh', 10.55, 'yes'),
 (54.19, 'no', 'Elblag', 9.82, 'yes'),
 (54.19, 'no', 'Elblag', 10.55, 'yes'),
 (50.97, 'no', 'Erfurt', 9.82, 'yes'),
 (50.97, 'no', 'Erfurt', 10.55, 'yes'),
 (50.7, 'no', 'Exeter', 9.82, 'yes'),
 (50.7, 'no', 'Exeter', 10.55, 'yes'),
 (50.1, 'no', 'Frankfurt', 9.82, 'yes'),
 (50.1, 'no', 'Frankfurt', 10.55, 'yes'),
 (48.0, 'no', 'Freiburg', 9.82, 'yes'),
 (48.0, 'no', 'Freiburg', 10.55, 'yes'),
 (53.27, 'no', 'Galway', 9.82, 'yes'),
 (53.27, 'no', 'Galway', 10.55, 'yes'),
 (46.21, 'no', 'Geneva', 9.82, 'yes'),
 (46.21, 'no', 'Geneva', 10.55, 'yes'),
 (55.87, 'no', 'Glasgow', 9.82, 'yes'),
 (55.87, 'no', 'Glasgow', 10.55, 'yes'),
 (57.75, 'no', 'Göteborg', 9.82, 'yes'),
 (57.75, 'no', 'Göteborg', 10.55, 'yes'),
 (47.08, 'no', 'Graz', 9.82, 'yes'),
 (47.08, 'no', 'Graz', 10.55, 'yes'),
 (45.18, 'no', 'Grenoble', 9.82, 'yes'),
 (45.18, 'no', 'Grenoble', 10.55, 'yes'),
 (53.22, 'no', 'Groningen', 9.82, 'yes'),
 (53.22, 'no', 'Groningen', 10.55, 'yes'),
 (47.7, 'no', 'Gyor', 9.82, 'yes'),
 (47.7, 'no', 'Gyor', 10.55, 'yes'),
 (49.42, 'no', 'Heidelberg', 9.82, 'yes'),
 (49.42, 'no', 'Heidelberg', 10.55, 'yes'),
 (60.18, 'no', 'Helsinki', 9.82, 'yes'),
 (60.18, 'no', 'Helsinki', 10.55, 'yes'),
 (48.3, 'no', 'Horlivka', 9.82, 'yes'),
 (48.3, 'no', 'Horlivka', 10.55, 'yes'),
 (53.68, 'no', 'Hrodna', 9.82, 'yes'),
 (53.68, 'no', 'Hrodna', 10.55, 'yes'),
 (48.77, 'no', 'Ingolstadt', 9.82, 'yes'),
 (48.77, 'no', 'Ingolstadt', 10.55, 'yes'),
 (47.28, 'no', 'Innsbruck', 9.82, 'yes'),
 (47.28, 'no', 'Innsbruck', 10.55, 'yes'),
 (57.47, 'no', 'Inverness', 9.82, 'yes'),
 (57.47, 'no', 'Inverness', 10.55, 'yes'),
 (49.0, 'no', 'Karlsruhe', 9.82, 'yes'),
 (49.0, 'no', 'Karlsruhe', 10.55, 'yes'),
 (54.95, 'no', 'Kaunas', 9.82, 'yes'),
 (54.95, 'no', 'Kaunas', 10.55, 'yes'),
 (46.63, 'no', 'Kherson', 9.82, 'yes'),
 (46.63, 'no', 'Kherson', 10.55, 'yes'),
 (50.89, 'no', 'Kielce', 9.82, 'yes'),
 (50.89, 'no', 'Kielce', 10.55, 'yes'),
 (50.43, 'no', 'Kiev', 9.82, 'yes'),
 (50.43, 'no', 'Kiev', 10.55, 'yes'),
 (67.85, 'no', 'Kiruna', 9.82, 'yes'),
 (67.85, 'no', 'Kiruna', 10.55, 'yes'),
 (55.72, 'no', 'Klaipeda', 9.82, 'yes'),
 (55.72, 'no', 'Klaipeda', 10.55, 'yes'),
 (48.73, 'no', 'Kosice', 9.82, 'yes'),
 (48.73, 'no', 'Kosice', 10.55, 'yes'),
 (54.2, 'no', 'Koszalin', 9.82, 'yes'),
 (54.2, 'no', 'Koszalin', 10.55, 'yes'),
 (49.08, 'no', 'Kremenchuk', 9.82, 'yes'),
 (49.08, 'no', 'Kremenchuk', 10.55, 'yes'),
 (47.93, 'no', 'Kryvyy Rih', 9.82, 'yes'),
 (47.93, 'no', 'Kryvyy Rih', 10.55, 'yes'),
 (48.0, 'no', 'Le Mans', 9.82, 'yes'),
 (48.0, 'no', 'Le Mans', 10.55, 'yes'),
 (50.65, 'no', 'Lille', 9.82, 'yes'),
 (50.65, 'no', 'Lille', 10.55, 'yes'),
 (45.83, 'no', 'Limoges', 9.82, 'yes'),
 (45.83, 'no', 'Limoges', 10.55, 'yes'),
 (48.32, 'no', 'Linz', 9.82, 'yes'),
 (48.32, 'no', 'Linz', 10.55, 'yes'),
 (46.06, 'no', 'Ljubljana', 9.82, 'yes'),
 (46.06, 'no', 'Ljubljana', 10.55, 'yes'),
 (49.83, 'no', 'Lvov', 9.82, 'yes'),
 (49.83, 'no', 'Lvov', 10.55, 'yes'),
 (50.85, 'no', 'Maastricht', 9.82, 'yes'),
 (50.85, 'no', 'Maastricht', 10.55, 'yes'),
 (52.13, 'no', 'Magdeburg', 9.82, 'yes'),
 (52.13, 'no', 'Magdeburg', 10.55, 'yes'),
 (48.03, 'no', 'Makiyivka', 9.82, 'yes'),
 (48.03, 'no', 'Makiyivka', 10.55, 'yes'),
 (55.58, 'no', 'Malmö', 9.82, 'yes'),
 (55.58, 'no', 'Malmö', 10.55, 'yes'),
 (52.05, 'no', 'Mazyr', 9.82, 'yes'),
 (52.05, 'no', 'Mazyr', 10.55, 'yes'),
 (49.12, 'no', 'Metz', 9.82, 'yes'),
 (49.12, 'no', 'Metz', 10.55, 'yes'),
 (45.47, 'no', 'Milan', 9.82, 'yes'),
 (45.47, 'no', 'Milan', 10.55, 'yes'),
 (53.9, 'no', 'Minsk', 9.82, 'yes'),
 (53.9, 'no', 'Minsk', 10.55, 'yes'),
 (47.75, 'no', 'Mulhouse', 9.82, 'yes'),
 (47.75, 'no', 'Mulhouse', 10.55, 'yes'),
 (45.25, 'no', 'Novi Sad', 9.82, 'yes'),
 (45.25, 'no', 'Novi Sad', 10.55, 'yes'),
 (55.4, 'no', 'Odense', 9.82, 'yes'),
 (55.4, 'no', 'Odense', 10.55, 'yes'),
 (54.52, 'no', 'Orsha', 9.82, 'yes'),
 (54.52, 'no', 'Orsha', 10.55, 'yes'),
 (59.92, 'no', 'Oslo', 9.82, 'yes'),
 (59.92, 'no', 'Oslo', 10.55, 'yes'),
 (49.83, 'no', 'Ostrava', 9.82, 'yes'),
 (49.83, 'no', 'Ostrava', 10.55, 'yes'),
 (65.0, 'no', 'Oulu', 9.82, 'yes'),
 (65.0, 'no', 'Oulu', 10.55, 'yes'),
 (52.13, 'no', 'Pinsk', 9.82, 'yes'),
 (52.13, 'no', 'Pinsk', 10.55, 'yes'),
 (52.41, 'no', 'Poznan', 9.82, 'yes'),
 (52.41, 'no', 'Poznan', 10.55, 'yes'),
 (50.08, 'no', 'Prague', 9.82, 'yes'),
 (50.08, 'no', 'Prague', 10.55, 'yes'),
 (49.25, 'no', 'Reims', 9.82, 'yes'),
 (49.25, 'no', 'Reims', 10.55, 'yes'),
 (56.95, 'no', 'Riga', 9.82, 'yes'),
 (56.95, 'no', 'Riga', 10.55, 'yes'),
 (45.33, 'no', 'Rijeka', 9.82, 'yes'),
 (45.33, 'no', 'Rijeka', 10.55, 'yes'),
 (50.62, 'no', 'Rivne', 9.82, 'yes'),
 (50.62, 'no', 'Rivne', 10.55, 'yes'),
 (54.07, 'no', 'Rostock', 9.82, 'yes'),
 (54.07, 'no', 'Rostock', 10.55, 'yes'),
 (47.81, 'no', 'Salzburg', 9.82, 'yes'),
 (47.81, 'no', 'Salzburg', 10.55, 'yes'),
 (45.8, 'no', 'Sibiu', 9.82, 'yes'),
 (45.8, 'no', 'Sibiu', 10.55, 'yes'),
 (58.97, 'no', 'Stavanger', 9.82, 'yes'),
 (58.97, 'no', 'Stavanger', 10.55, 'yes'),
 (59.35, 'no', 'Stockholm', 9.82, 'yes'),
 (59.35, 'no', 'Stockholm', 10.55, 'yes'),
 (50.92, 'no', 'Sumy', 9.82, 'yes'),
 (50.92, 'no', 'Sumy', 10.55, 'yes'),
 (51.63, 'no', 'Swansea', 9.82, 'yes'),
 (51.63, 'no', 'Swansea', 10.55, 'yes'),
 (46.25, 'no', 'Szeged', 9.82, 'yes'),
 (46.25, 'no', 'Szeged', 10.55, 'yes'),
 (59.43, 'no', 'Tallinn', 9.82, 'yes'),
 (59.43, 'no', 'Tallinn', 10.55, 'yes'),
 (61.5, 'no', 'Tampere', 9.82, 'yes'),
 (61.5, 'no', 'Tampere', 10.55, 'yes'),
 (58.38, 'no', 'Tartu', 9.82, 'yes'),
 (58.38, 'no', 'Tartu', 10.55, 'yes'),
 (45.65, 'no', 'Trieste', 9.82, 'yes'),
 (45.65, 'no', 'Trieste', 10.55, 'yes'),
 (63.42, 'no', 'Trondheim', 9.82, 'yes'),
 (63.42, 'no', 'Trondheim', 10.55, 'yes'),
 (60.45, 'no', 'Turku', 9.82, 'yes'),
 (60.45, 'no', 'Turku', 10.55, 'yes'),
 (59.86, 'no', 'Uppsala', 9.82, 'yes'),
 (59.86, 'no', 'Uppsala', 10.55, 'yes'),
 (48.2, 'no', 'Vienna', 9.82, 'yes'),
 (48.2, 'no', 'Vienna', 10.55, 'yes'),
 (54.68, 'no', 'Vilnius', 9.82, 'yes'),
 (54.68, 'no', 'Vilnius', 10.55, 'yes'),
 (52.25, 'no', 'Warsaw', 9.82, 'yes'),
 (52.25, 'no', 'Warsaw', 10.55, 'yes'),
 (51.11, 'no', 'Wroclaw', 9.82, 'yes'),
 (51.11, 'no', 'Wroclaw', 10.55, 'yes'),
 (45.2, 'no', 'Yevpatoriya', 9.82, 'yes'),
 (45.2, 'no', 'Yevpatoriya', 10.55, 'yes'),
 (50.25, 'no', 'Zhytomyr', 9.82, 'yes'),
 (50.25, 'no', 'Zhytomyr', 10.55, 'yes'),
 (47.38, 'no', 'Zurich', 9.82, 'yes'),
 (47.38, 'no', 'Zurich', 10.55, 'yes')]

### Aggregation and Grouping

*Find the average temperature for all cities*

In [27]:
%%sql
select avg(temperature)
from Cities

 * sqlite://
Done.

[(9.497840375586858,)]

*Modify previous query to find average temperature of cities with latitude > 55*

*Modify previous query to also find minimum and maxiumum temperature of cities with latitude > 55*

*Modify previous query to return number of cities with latitude > 55*

*Rename result column as northerns*

*Find the minimum and maximum temperature of cities in the EU (then not in the EU)*

In [30]:
%%sql
select min(temperature), max(temperature)
from Cities, Countries
where Cities.country = Countries.Country
and EU = 'yes'

 * sqlite://
Done.

[(-2.2, 17.9)]

### <font color = 'green'>**Your Turn**</font>

*Find the number of cities with latitude > 45 in countries with no coastline and with population > 9; also return the minimum and maximum latitude among those cities*

In [31]:
%%sql
select min(latitude), max(latitude)
from Cities, Countries
where latitude > 45 and coastline = 'no' and population > 9
and EU = 'yes'

 * sqlite://
Done.

[(45.18, 67.85)]

*Find the average temperature for each country*

In [33]:
%%sql
select country, avg(temperature)
from Cities
group by country

 * sqlite://
Done.

[('Albania', 15.18),
 ('Andorra', 9.6),
 ('Austria', 6.144),
 ('Belarus', 5.946666666666666),
 ('Belgium', 9.65),
 ('Bosnia and Herzegovina', 9.6),
 ('Bulgaria', 10.44),
 ('Croatia', 10.865),
 ('Czech Republic', 7.8566666666666665),
 ('Denmark', 7.625),
 ('Estonia', 4.59),
 ('Finland', 3.4875),
 ('France', 10.151111111111112),
 ('Germany', 7.869285714285714),
 ('Greece', 16.9025),
 ('Hungary', 9.6025),
 ('Ireland', 9.299999999999999),
 ('Italy', 13.474666666666668),
 ('Latvia', 5.27),
 ('Lithuania', 6.1433333333333335),
 ('Macedonia', 9.36),
 ('Moldova', 8.415),
 ('Montenegro', 9.99),
 ('Netherlands', 8.756666666666668),
 ('Norway', 3.7260000000000004),
 ('Poland', 7.250000000000002),
 ('Portugal', 14.469999999999999),
 ('Romania', 9.224444444444444),
 ('Serbia', 9.85),
 ('Slovakia', 8.48),
 ('Slovenia', 9.27),
 ('Spain', 14.238333333333332),
 ('Sweden', 3.5866666666666673),
 ('Switzerland', 7.253333333333333),
 ('Turkey', 11.726666666666665),
 ('Ukraine', 7.420000000000002),
 ('United Kingdom', 8.649999999999999)]

*Modify previous query to sort by descending average temperature*

*Modify previous query to show countries only*

*Find the average temperature for cities in countries with and without coastline*

In [32]:
%%sql
select coastline, avg(temperature)
from Cities, Countries
where Cities.country = Countries.country
group by coastline

 * sqlite://
Done.

[('no', 7.748000000000001), ('yes', 9.784699453551914)]

*Modify previous query to find the average temperature for cities in the EU and not in the EU, then all combinations of coastline and EU*

*Modify previous query to only include cities with latitude < 50, then latitude < 40*

### <font color = 'green'>**Your Turn**</font>

*For each country in the EU, find the latitude of the northernmost city in the country, i.e., the maximum latitude. Return the country and its maximum latitude, in descending order of maximum latitude.*

In [45]:
%%sql
select Cities.country, max(latitude) as northenmost
from Cities, Countries
where Cities.country = Countries.country
and EU='yes'
group by Cities.country
order by max(latitude) desc

 * sqlite://
Done.

[('Sweden', 67.85),
 ('Finland', 65.0),
 ('Estonia', 59.43),
 ('United Kingdom', 57.47),
 ('Denmark', 57.03),
 ('Latvia', 56.95),
 ('Lithuania', 55.72),
 ('Poland', 54.2),
 ('Germany', 54.07),
 ('Ireland', 53.33),
 ('Netherlands', 53.22),
 ('Belgium', 51.22),
 ('France', 50.65),
 ('Czech Republic', 50.08),
 ('Slovakia', 48.73),
 ('Austria', 48.32),
 ('Romania', 47.75),
 ('Hungary', 47.7),
 ('Slovenia', 46.06),
 ('Italy', 45.7),
 ('Croatia', 45.33),
 ('Bulgaria', 43.85),
 ('Spain', 43.38),
 ('Portugal', 41.55),
 ('Greece', 39.56)]

#### A Bug in SQLight - just FYI

In [46]:
%%sql
select country, avg(temperature)
from Cities
group by country

 * sqlite://
Done.

[('Albania', 15.18),
 ('Andorra', 9.6),
 ('Austria', 6.144),
 ('Belarus', 5.946666666666666),
 ('Belgium', 9.65),
 ('Bosnia and Herzegovina', 9.6),
 ('Bulgaria', 10.44),
 ('Croatia', 10.865),
 ('Czech Republic', 7.8566666666666665),
 ('Denmark', 7.625),
 ('Estonia', 4.59),
 ('Finland', 3.4875),
 ('France', 10.151111111111112),
 ('Germany', 7.869285714285714),
 ('Greece', 16.9025),
 ('Hungary', 9.6025),
 ('Ireland', 9.299999999999999),
 ('Italy', 13.474666666666668),
 ('Latvia', 5.27),
 ('Lithuania', 6.1433333333333335),
 ('Macedonia', 9.36),
 ('Moldova', 8.415),
 ('Montenegro', 9.99),
 ('Netherlands', 8.756666666666668),
 ('Norway', 3.7260000000000004),
 ('Poland', 7.250000000000002),
 ('Portugal', 14.469999999999999),
 ('Romania', 9.224444444444444),
 ('Serbia', 9.85),
 ('Slovakia', 8.48),
 ('Slovenia', 9.27),
 ('Spain', 14.238333333333332),
 ('Sweden', 3.5866666666666673),
 ('Switzerland', 7.253333333333333),
 ('Turkey', 11.726666666666665),
 ('Ukraine', 7.420000000000002),
 ('United Kingdom', 8.649999999999999)]

*Modify previous query - add city to Select clause*

*Now focus on Austria and Sweden*

In [ ]:
%%sql
select *
from Cities
where country = 'Austria' or country = 'Sweden'
order by country

In [ ]:
%%sql
select country, city, avg(temperature)
from Cities
where country = 'Austria' or country = 'Sweden'
group by country

*Modify previous query to min(temperature), max(temperature), then together in both orders*

### The Limit clause

*Return any three countries with population > 20*

In [47]:
%%sql
select country
from Countries
where population > 20
limit 3

 * sqlite://
Done.

[('France',), ('Germany',), ('Italy',)]

*Find the ten coldest cities*

In [48]:
%%sql
select city, temperature
from Cities
order by temperature
limit 10

 * sqlite://
Done.

[('Kiruna', -2.2),
 ('Abisko', 0.2),
 ('Oulu', 1.45),
 ('Bergen', 1.75),
 ('Oslo', 2.32),
 ('Tampere', 3.59),
 ('Uppsala', 4.17),
 ('Helsinki', 4.19),
 ('Tartu', 4.36),
 ('Bodo', 4.5)]

### <font color = 'green'>**Your Turn**</font>

*Find the five easternmost (greatest longitude) cities in countries with no coastline. Return the city and country names.*

In [58]:
%%sql
select city, Cities.country
from Countries, Cities
where Cities.country = Countries.country and coastline = 'no'
order by longitude desc
limit 5

 * sqlite://
Done.

[('Orsha', 'Belarus'),
 ('Mazyr', 'Belarus'),
 ('Chisinau', 'Moldova'),
 ('Balti', 'Moldova'),
 ('Minsk', 'Belarus')]

### <font color = 'green'>**Your Turn - Basic SQL on World Cup Data**</font>

In [60]:
# Upload world cup data files
# Choose files Players.csv and Teams.csv - must be on local computer
from google.colab import files
uploaded = files.upload()
# Then load tables from CSV files
with open('Players.csv') as f: Players = pd.read_csv(f, index_col=0)
%sql drop table if exists Players;
%sql --persist Players
with open('Teams.csv') as f: Teams = pd.read_csv(f, index_col=0)
%sql drop table if exists Teams;
%sql --persist Teams

Saving Players.csv to Players (1).csv
Saving Teams.csv to Teams (1).csv
 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.
 * sqlite://

'Persisted teams'

#### Look at sample of Players and Teams tables

In [61]:
%%sql
select * from Players limit 5

 * sqlite://
Done.

[('Abdoun', 'Algeria', 'midfielder', 16, 0, 6, 0, 0),
 ('Belhadj', 'Algeria', 'defender', 270, 1, 146, 8, 0),
 ('Boudebouz', 'Algeria', 'midfielder', 74, 3, 28, 1, 0),
 ('Bougherra', 'Algeria', 'defender', 270, 1, 89, 11, 0),
 ('Chaouchi', 'Algeria', 'goalkeeper', 90, 0, 17, 0, 2)]

In [62]:
%%sql
select * from Teams limit 5

 * sqlite://
Done.

[('Brazil', 1, 5, 3, 1, 1, 9, 4, 7, 2),
 ('Spain', 2, 6, 5, 0, 1, 7, 2, 3, 0),
 ('Portugal', 3, 4, 1, 2, 1, 7, 1, 8, 1),
 ('Netherlands', 4, 6, 6, 0, 0, 12, 5, 15, 0),
 ('Italy', 5, 3, 0, 2, 1, 4, 5, 5, 0)]

*1)  What player on a team with “ia” in the team name played less than 200 minutes and made more than 100 passes? Return the player surname. Note: To check if attribute A contains string S use "A like '%S%'"*

In [63]:
%%sql
SELECT surname 
FROM players 
WHERE team LIKE '%ia%' 
  AND minutes < 200 
  AND passes > 100;

 * sqlite://
Done.

[('Kuzmanovic',)]

*2) Find all players who made more than 20 shots. Return all player information in descending order of shots made.*

In [64]:
%%sql
SELECT *
FROM players
WHERE shots > 20
ORDER BY shots DESC;

 * sqlite://
Done.

[('Gyan', 'Ghana', 'forward', 501, 27, 151, 1, 0),
 ('Villa', 'Spain', 'forward', 529, 22, 169, 2, 0),
 ('Messi', 'Argentina', 'forward', 450, 21, 321, 10, 0)]

*3) Find the goalkeepers of teams that played more than four games. List the surname of the goalkeeper, the team, and the number of minutes the goalkeeper played.*

In [66]:
%%sql
SELECT surname, team, minutes
FROM players
WHERE position = 'goalkeeper' 
  AND team IN (SELECT team FROM teams WHERE games > 4) 
ORDER BY team;

 * sqlite://
Done.

[('Romero', 'Argentina', 450),
 ('Julio Cesar', 'Brazil', 450),
 ('Neuer', 'Germany', 540),
 ('Kingson', 'Ghana', 510),
 ('Stekelenburg', 'Netherlands', 540),
 ('Villar', 'Paraguay', 480),
 ('Casillas', 'Spain', 540),
 ('Muslera', 'Uruguay', 570)]

*4) How many players who play on a team with ranking <10 played more than 350 minutes? Return one number in a column named 'superstar'.*

In [67]:
%%sql
SELECT COUNT(*) as superstar
FROM players
WHERE team IN (
  SELECT team
  FROM teams
  WHERE ranking < 10
)
AND minutes > 350;

 * sqlite://
Done.

[(54,)]

*5) What is the average number of passes made by forwards? By midfielders? Write one query that gives both values with the corresponding position.*

In [68]:
%%sql

 * sqlite://
Done.

[('Spain', 0.6230639730639731)]

*6) Which team has the highest average number of passes per minute played? Return the team and average passes per minute. Hints: (1) You can compute a team's average number of passes per minute played by dividing the total number of passes by the total number of minutes. To force floating point division, multiply one operand by 1.0. (2) Consider using Limit.*

In [69]:
%%sql
SELECT team, SUM(passes) / (SUM(minutes) * 1.0) as avg_passes_per_minute
FROM players
GROUP BY team
ORDER BY avg_passes_per_minute DESC
LIMIT 1

 * sqlite://
Done.

[('Spain', 0.6230639730639731)]

### <font color = 'green'>**Your Turn Extra - Basic SQL on Titanic Data**</font>

In [72]:
# Upload Titanic data file
# Choose file Titanic.csv - must be on local computer
from google.colab import files
uploaded = files.upload()
# Then load table from CSV file
with open('Titanic.csv') as f: Titanic = pd.read_csv(f, index_col=0)
%sql drop table if exists Titanic;
%sql --persist Titanic

Saving Titanic.csv to Titanic (1).csv
 * sqlite://
Done.
 * sqlite://

'Persisted titanic'

#### Look at sample of Titanic table

In [73]:
%%sql
select * from Titanic limit 5

 * sqlite://
Done.

[('Abbing', 'Mr. Anthony', 'M', 42.0, 3, 7.55, 'Southampton', 'no'),
 ('Abbott', 'Mrs. Stanton (Rosa Hunt)', 'F', 35.0, 3, 20.25, 'Southampton', 'yes'),
 ('Abbott', 'Mr. Rossmore Edward', 'M', 16.0, 3, 20.25, 'Southampton', 'no'),
 ('Abelson', 'Mr. Samuel', 'M', 30.0, 2, 24.0, 'Cherbourg', 'no'),
 ('Abelson', 'Mrs. Samuel (Hannah Wizosky)', 'F', 28.0, 2, 24.0, 'Cherbourg', 'yes')]

*1) How many passengers sailed for free (i.e, fare is zero)?*

In [76]:
%%sql
select count(*) as passengers_sailed_for_free 
from Titanic 
where fare = 0

 * sqlite://
Done.

[(15,)]

*2) How many married women over age 50 embarked in Cherbourg? (Married women’s first names begin with "Mrs."). Note: To check if attribute A begins with string S use "A like 'S%'"*

In [ ]:
%%sql

*3) Write three queries to find: (i) the total number of passengers; (ii) the number of passengers under 18; (iii) the number of passengers 18 or older. Notice that the second and third numbers don't add up to the first.*

In [ ]:
%%sql
YOUR FIRST QUERY HERE

In [ ]:
%%sql
YOUR SECOND QUERY HERE

In [ ]:
%%sql
YOUR THIRD QUERY HERE

*Missing values in SQL tables are given a special value called 'null', and conditions 'A is null' and 'A is not null' can be use in Where clauses to check whether attribute A has the 'null' value. Write a query to find the number of passengers whose age is missing -- now your passenger numbers should add up. Modify the query to also return the average fare paid by those passengers.*

In [ ]:
%%sql
YOUR QUERY HERE

*4) Find all passengers whose age is not an integer; return last name, first name, and age, from youngest to oldest. Note: Consider using the round() function*

In [ ]:
%%sql
YOUR QUERY HERE

*5) What is the most common last name among passengers, and how many passengers have that last name?*

In [ ]:
%%sql
YOUR QUERY HERE

*6) What is the average fare paid by passengers in the three classes, and the average age of passengers in the three classes?*

In [ ]:
%%sql
YOUR QUERY HERE

*7) For male survivors, female survivors, male non-survivors, and female non-survivors, how many passengers are in each of those four categories and what is their average fare? Return your results from lowest to highest
average fare.*

In [ ]:
%%sql
YOUR QUERY HERE